### PR TITLE
Create a base docker image with dependancies

### PR DESCRIPTION
**Pull request by srleyva**
* This means the docker image won't have to
  build dependacies and should shorten the
  docker build to a few seconds

@jbixon13

### CODE REVIEW

**Review by jbixon13 — APPROVED** [review]
Thanks for the help! One question you may be able to help me with is the point of failure I'm having with the Heroku deployment. When I push new changes to the Github repo they do not show up on the app itself, I assume this is because the app is built using a container and not from Github directly. 

Is the root cause of the issue that I need to re-build/re-deploy the Heroku app after I've pushed changes to Github, and if so how can I set up some CD process that would work similarly to if I linked the repo to the Heroku app directly?

**Comment by srleyva** [comment]
Sure I don't mind trying to assist on that @jbixon13

**Comment by madhuravius** [comment]
@srleyva this the equivalent of basically using the docker image i posted earlier. This isn't really what would address the issue.  If Jason (or another dev) adds dependencies, this image will always fail. 

What I was trying to say was basically the packrat file needs to be generated if there are any dependency changes and then the subsequent dependencies need to be installed to the image, and you can't know unless you have access to the code.  Many of the dependencies in R are pretty naive too, because they require deps like: `libcairo2-dev` (I think for some specific fonts?). 

I think the real way to do this would be to break the image at line 26 of the .base:

```
RUN R -e 'install.packages("packrat" , repos="http://cran.us.r-project.org"); packrat::restore()'
```

Run those IF there are any dependencies changed, and then start the app in a secondary image. In an equivalent, this is like pulling out the npm install out of a build (it would be catastrophic if any dependencies changed). 

Edit: Perhaps we could address this in .travis.yml by adding a check (if dependencies change) to recreate the base image and upload that?

**Comment by srleyva** [comment]
That was a concern we noted and some tech debt we said we could take on. The idea being that we can always rebuild the base image manually if new dependencies are introduced and while this is definitely not ideal...a 30-minute constraint in the pipeline we're working on for builds would also be frustrating for deployments when the dependencies don't change (from talking it doesn't sound like they change often).

I agree that adding a check for dependencies and rebuilding if necessary is the ideal solution. This is just a workaround that adds some tech debt but it can help with the long builds until a solution can be built out.

I am working on the pipeline (#9)  this weekend. Is there an issue for that particular solution that we can perhaps incorporate? @madhuravius

**Comment by madhuravius** [comment]
If that's the case this is totally going to suit what we need. I just recall every group of commits (on a weekly basis or so?) was having dependency changes. Might be a blocker if you have to build every time. Maybe another possible test is just seeing if the app starts in CI and doing /get calls with curl to each view expecting 200s? (so we know to push another image) https://github.com/syncthecity/shinymap/issues/9

I think there's another ticket for the Ci/CD (if that's what you meant by issue). I was hoping for someone to grab it so I'm very happy you've opted to take it :D

**Comment by srleyva** [comment]
I am all for adding integration tests 😄I was thinking the flow (and my knowledge of packrat for managing R dependencies is limited so please feel free to change this) would be:
1. Run `git log -m -1 --name-only --pretty="format:"` to get the list of changed files in the merge.
2. If packrat dependancies are included rerun through the build process for the base image if not continue.
3. Rebuild the app image with the new image.

I do like the idea of checking for 200s in the response using Docker compose or something either way before promoting to prod. Your thoughts and opinions on this flow are more than welcome! @madhuravius

**Comment by jbixon13** [comment]
@madhuravius how did you set up the packrat file in the first place? I'm not familiar with using it for dependencies but if you have resources on how I would re-create it when new deps are added that would help. Is it automatically built based on .rproj or similar environment files?

**Pull request merged**
